/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qkartaudit;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;

import javax.imageio.ImageIO;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;


import java.util.*;
import org.json.simple.*;
import org.json.simple.parser.*;

import io.github.bonigarcia.wdm.WebDriverManager;
import ru.yandex.qatools.ashot.AShot;
import ru.yandex.qatools.ashot.Screenshot;
import ru.yandex.qatools.ashot.shooting.ShootingStrategies;

public class App {
   
public static ChromeDriver createDriver() {
        //TODO Create a new chrome Driver and Return the same
        WebDriverManager.chromedriver().setup();

        ChromeOptions options = new ChromeOptions();
		options.addArguments("--remote-allow-origins=*", "--headless", "--window-size=1920,1200");


        ChromeDriver driver = new ChromeDriver(options);
        return driver;
    }

    public static void printQKartLoadingtime(ChromeDriver driver) throws IOException, ParseException{
        //TODO Navigate to home page of QKart and verify the time taken for the page to load

        long start = System.currentTimeMillis();
        
        JSONParser parser = new JSONParser();
        // Read the JSON file and pass it to the parser.
        FileReader reader = new FileReader("config.json");
        Object obj = parser.parse(reader);

        JSONObject object = (JSONObject) obj;

        // Get the values of the various fields.
        String URL = (String) object.get("QKART_URL");
        
        driver.get(URL);
        WebDriverWait wait = new WebDriverWait(driver, 10L);
        wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//p[text()='Jenga']/../..//img")));

        long end = System.currentTimeMillis();
        //finding the time difference and converting it into seconds
        float sec = (end - start) / 1000F; 
      
        System.out.println("Time taken to load QKart Page : "+ sec);

    }

    public static void captureFullPageScreenshot(ChromeDriver driver) throws IOException, ParseException{
        //TODO: Capture the full page screenshot
        //Save the file with a unique name

        String timeStamp = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new java.util.Date());

        // Print the path of the file
        Screenshot screenshot = new AShot().shootingStrategy(ShootingStrategies.viewportPasting(1000)).takeScreenshot(driver);

        JSONParser parser = new JSONParser();
        // Read the JSON file and pass it to the parser.
        FileReader reader = new FileReader("config.json");
        Object obj = parser.parse(reader);

        JSONObject object = (JSONObject) obj;

        // Get the values of the various fields.
        String ScreenshotSaveLocation = (String) object.get("ScreenshotSaveLocation");

        ImageIO.write(screenshot.getImage(), "png", new File(ScreenshotSaveLocation + "/" + timeStamp + ".png"));

        System.out.println("Full Page Screenshot captured and saved at : "+ timeStamp + ".png");
    }   

    public static void GetProductImageandURL(ChromeDriver driver, String productName) throws InterruptedException{
        //TODO: Given the product name, print the price of the project and the url of the image

        WebElement product = driver.findElement(By.xpath("//p[text()='"+ productName +"']/../.."));

        String price = product.findElement(By.xpath(".//p[contains(@class,'uickyz')]")).getText();

        String imgURL = product.findElement(By.xpath(".//img")).getAttribute("src");

        System.out.println("Price of the product is : "+ price);
        System.out.println("URL of the Product Image is : "+ imgURL);
    }

    public static void main(String[] args) {
        ChromeDriver driver = createDriver();
        String input = String.join(" ", args );
        try{

            printQKartLoadingtime(driver);

            captureFullPageScreenshot(driver);
            
            GetProductImageandURL(driver,input );
            
        }catch(Exception e)
        {
            System.out.println(e.getMessage());
        }finally{
            driver.quit();
        }
    }
}
